### ISSUE TITLE
version issue in 1.79.2

### ISSUE THREAD

**Issue by liebespaar93** [ByPikod/markdown-it-github-alert#3]
### Hi!
Thank U for make this editor

## 1. 🤔 version issue

i use in 42seoul mac but there are not update version of vscode
so i can't use it.. can U support low version?

<img width="425" alt="image" src="https://github.com/ByPikod/markdown-it-github-alert/assets/82822684/00645931-73c4-4574-8132-3a506ae21540">

## 2. 🤔 white space check
> [!Note] 
> space check!

it need to be perfectly clean next side of alert
it little bit not comfortable

**Comment by ByPikod** [comment]
# Version issue
I am not quite sure why its happening. I will look into it.

# White space check
I can't tell I understand the issue here. Can you make it more clear?

**Comment by liebespaar93** [comment]
like this
'''markdown
> [!NOTE] <- add space and /n
> hi

'''

I tests in m1 macbook air
os is lastest

**Comment by ByPikod** [comment]
Apparently latest version of VS Code is 1.83. Considering my extension just published, you might need to update your editor.

Beside that I still didn't understand your issue. Perhaps you can use ChatGPT to translate the issue to English from your native language.

**Comment by liebespaar93** [comment]
![issue](https://github.com/ByPikod/markdown-it-github-alert/assets/82822684/4413973a-a5da-472a-ab4b-89e0162117d7)
like this happen! i like too input space after [] this basket
thank U for read~ 😆

**Comment by ByPikod** [comment]
I see

**Comment by ByPikod** [comment]
Hello again!

Here problem solved:
Commit: https://github.com/ByPikod/markdown-it-github-alert/commit/62161165caba757c4f53f91a6fec5baa7732034c
Extension Release: https://github.com/ByPikod/vscode-markdown-alert/releases/tag/v1.0.4

Thank you for letting me know the issue. And I appereciate the effort you put to make me understand the issue 😂

![resim](https://github.com/ByPikod/markdown-it-github-alert/assets/46069238/17f5203d-fe96-44ac-ab76-9a81f75613a8)

Have a great day!

**Comment by liebespaar93** [comment]
nice! thank U ~
